//Skill
export const CREATE_SKILL = "CREATE_SKILL"
export const CREATE_SKILL_RED = "CREATE_SKILL_RED"
export const GET_SKILL = "GET_SKILL"
export const GET_SKILL_RED = "GET_SKILL_RED"
export const UPDATE_SKILL = "UPDATE_SKILL"
export const UPDATE_SKILL_RED = "UPDATE_SKILL_RED"
export const DELETE_SKILL = "DELETE_SKILL"
export const DELETE_SKILL_RED = "DELETE_SKILL_RED"


//PORTFOLIO
export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO"
export const CREATE_PORTFOLIO_RED = "CREATE_PORTFOLIO_RED"
export const GET_PORTFOLIO = "GET_PORTFOLIO"
export const GET_PORTFOLIO_RED = "GET_PORTFOLIO_RED"
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO"
export const UPDATE_PORTFOLIO_RED = "UPDATE_PORTFOLIO_RED"
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO"
export const DELETE_PORTFOLIO_RED = "DELETE_PORTFOLIO_RED"


//CERTIFICATE
export const CREATE_CERTIFICATE = "CREATE_CERTIFICATE"
export const CREATE_CERTIFICATE_RED = "CREATE_CERTIFICATE_RED"
export const GET_CERTIFICATE = "GET_CERTIFICATE"
export const GET_CERTIFICATE_RED = "GET_CERTIFICATE_RED"
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE"
export const UPDATE_CERTIFICATE_RED = "UPDATE_CERTIFICATE_RED"
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE"
export const DELETE_CERTIFICATE_RED = "DELETE_CERTIFICATE_RED"


//EDUCATION
export const CREATE_EDUCATION = "CREATE_EDUCATION"
export const CREATE_EDUCATION_RED = "CREATE_EDUCATION_RED"
export const GET_EDUCATION = "GET_EDUCATION"
export const GET_EDUCATION_RED = "GET_EDUCATION_RED"
export const UPDATE_EDUCATION = "UPDATE_EDUCATION"
export const UPDATE_EDUCATION_RED = "UPDATE_EDUCATION_RED"
export const DELETE_EDUCATION = "DELETE_EDUCATION"
export const DELETE_EDUCATION_RED = "DELETE_EDUCATION_RED"


//EXPERIENCE
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE"
export const CREATE_EXPERIENCE_RED = "CREATE_EXPERIENCE_RED"
export const GET_EXPERIENCE = "GET_EXPERIENCE"
export const GET_EXPERIENCE_RED = "GET_EXPERIENCE_RED"
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE"
export const UPDATE_EXPERIENCE_RED = "UPDATE_EXPERIENCE_RED"
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE"
export const DELETE_EXPERIENCE_RED = "DELETE_EXPERIENCE_RED"

//SERVICE
export const CREATE_SERVICE = "CREATE_SERVICE"
export const CREATE_SERVICE_RED = "CREATE_SERVICE_RED"
export const GET_SERVICE = "GET_SERVICE"
export const GET_SERVICE_RED = "GET_SERVICE_RED"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const UPDATE_SERVICE_RED = "UPDATE_SERVICE_RED"
export const DELETE_SERVICE = "DELETE_SERVICE"
export const DELETE_SERVICE_RED = "DELETE_SERVICE_RED"

//TESTIMONIAL
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"

//Contact Us
export const CREATE_BLOG = "CREATE_BLOG"
export const CREATE_BLOG_RED = "CREATE_BLOG_RED"
export const GET_BLOG = "GET_BLOG"
export const GET_BLOG_RED = "GET_BLOG_RED"
export const UPDATE_BLOG = "UPDATE_BLOG"
export const UPDATE_BLOG_RED = "UPDATE_BLOG_RED"
export const DELETE_BLOG = "DELETE_BLOG"
export const DELETE_BLOG_RED = "DELETE_BLOG_RED"


//Contact Us
export const CREATE_CONTACT_US = "CREATE_CONTACT_US"
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED"
export const GET_CONTACT_US = "GET_CONTACT_US"
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED"
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US"
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED"
export const DELETE_CONTACT_US = "DELETE_CONTACT_US"
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED"

//Newsletter
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED = "CREATE_NEWSLETTER_RED"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED"
export const UPDATE_NEWSLETTER = "UPDATE_NEWSLETTER"
export const UPDATE_NEWSLETTER_RED = "UPDATE_NEWSLETTER_RED"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED"

export const CREATE_COMMENT = "CREATE_COMMENT"
export const CREATE_COMMENT_RED = "CREATE_COMMENT_RED"
export const GET_COMMENT = "GET_COMMENT"
export const GET_COMMENT_RED = "GET_COMMENT_RED"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const UPDATE_COMMENT_RED = "UPDATE_COMMENT_RED"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_RED = "DELETE_COMMENT_RED"

export const CREATE_ACHIEVEMENT = "CREATE_ACHIEVEMENT"
export const CREATE_ACHIEVEMENT_RED = "CREATE_ACHIEVEMENT_RED"
export const GET_ACHIEVEMENT = "GET_ACHIEVEMENT"
export const GET_ACHIEVEMENT_RED = "GET_ACHIEVEMENT_RED"
export const UPDATE_ACHIEVEMENT = "UPDATE_ACHIEVEMENT"
export const UPDATE_ACHIEVEMENT_RED = "UPDATE_ACHIEVEMENT_RED"
export const DELETE_ACHIEVEMENT = "DELETE_SKILL"
export const DELETE_ACHIEVEMENT_RED = "DELETE_ACHIEVEMENT_RED"

export const CREATE_ABOUT = "CREATE_ABOUT";
export const CREATE_ABOUT_RED = "CREATE_ABOUT_RED";
export const GET_ABOUT = "GET_ABOUT";
export const GET_ABOUT_RED = "GET_ABOUT_RED";
export const UPDATE_ABOUT = "UPDATE_ABOUT";
export const UPDATE_ABOUT_RED = "UPDATE_ABOUT_RED";
export const DELETE_ABOUT = "DELETE_ABOUT";
export const DELETE_ABOUT_RED = "DELETE_ABOUT_RED";

export const GET_RESUME = "GET_RESUME"
export const GET_RESUME_RED = "GET_RESUME_RED"

export const CREATE_CAREER = "CREATE_CAREER"
export const CREATE_CAREER_RED = "CREATE_CAREER_RED"
export const GET_CAREER = "GET_CAREER"
export const GET_CAREER_RED = "GET_CAREER_RED"
export const UPDATE_CAREER = "UPDATE_CAREER"
export const UPDATE_CAREER_RED = "UPDATE_CAREER_RED"
export const DELETE_CAREER = "DELETE_CAREER"
export const DELETE_CAREER_RED = "DELETE_CAREER_RED"

export const CREATE_PLACEMENT = "CREATE_PLACEMENT"
export const CREATE_PLACEMENT_RED = "CREATE_PLACEMENT_RED"
export const GET_PLACEMENT = "GET_PLACEMENT"
export const GET_PLACEMENT_RED = "GET_PLACEMENT_RED"
export const UPDATE_PLACEMENT = "UPDATE_PLACEMENT"
export const UPDATE_PLACEMENT_RED = "UPDATE_PLACEMENT_RED"
export const DELETE_PLACEMENT = "DELETE_PLACEMENT"
export const DELETE_PLACEMENT_RED = "DELETE_PLACEMENT_RED"

export const CREATE_TEAMS = "CREATE_TEAMS"
export const CREATE_TEAMS_RED = "CREATE_TEAMS_RED"
export const GET_TEAMS = "GET_TEAMS"
export const GET_TEAMS_RED = "GET_TEAMS_RED"
export const UPDATE_TEAMS = "UPDATE_TEAMS"
export const UPDATE_TEAMS_RED = "UPDATE_TEAMS_RED"
export const DELETE_TEAMS = "DELETE_TEAMS"
export const DELETE_TEAMS_RED = "DELETE_TEAMS_RED"

export const CREATE_BANNER = "CREATE_BANNER"
export const CREATE_BANNER_RED = "CREATE_BANNER_RED"
export const GET_BANNER = "GET_BANNER"
export const GET_BANNER_RED = "GET_BANNER_RED"
export const UPDATE_BANNER = "UPDATE_BANNER"
export const UPDATE_BANNER_RED = "UPDATE_BANNER_RED"
export const DELETE_BANNER = "DELETE_BANNER"
export const DELETE_BANNER_RED = "DELETE_BANNER_RED"

export const CREATE_WHYCHOOSEUS = "CREATE_WHYCHOOSEUS"
export const CREATE_WHYCHOOSEUS_RED = "CREATE_WHYCHOOSEUS_RED"
export const GET_WHYCHOOSEUS = "GET_WHYCHOOSEUS"
export const GET_WHYCHOOSEUS_RED = "GET_WHYCHOOSEUS_RED"
export const UPDATE_WHYCHOOSEUS = "UPDATE_WHYCHOOSEUS"
export const UPDATE_WHYCHOOSEUS_RED = "UPDATE_WHYCHOOSEUS_RED"
export const DELETE_WHYCHOOSEUS = "DELETE_WHYCHOOSEUS"
export const DELETE_WHYCHOOSEUS_RED = "DELETE_WHYCHOOSEUS_RED"

export const CREATE_TECHSTACK = "CREATE_TECHSTACK"
export const CREATE_TECHSTACK_RED = "CREATE_TECHSTACK_RED"
export const GET_TECHSTACK = "GET_TECHSTACK"
export const GET_TECHSTACK_RED = "GET_TECHSTACK_RED"
export const UPDATE_TECHSTACK = "UPDATE_TECHSTACK"
export const UPDATE_TECHSTACK_RED = "UPDATE_TECHSTACK_RED"
export const DELETE_TECHSTACK = "DELETE_TECHSTACK"
export const DELETE_TECHSTACK_RED = "DELETE_TECHSTACK_RED"


//SERVICE
export const CREATE_SUBSERVICE = "CREATE_SUBSERVICE"
export const CREATE_SUBSERVICE_RED = "CREATE_SUBSERVICE_RED"
export const GET_SUBSERVICE = "GET_SUBSERVICE"
export const GET_SUBSERVICE_RED = "GET_SUBSERVICE_RED"
export const UPDATE_SUBSERVICE = "UPDATE_SUBSERVICE"
export const UPDATE_SUBSERVICE_RED = "UPDATE_SUBSERVICE_RED"
export const DELETE_SUBSERVICE = "DELETE_SUBSERVICE"
export const DELETE_SUBSERVICE_RED = "DELETE_SUBSERVICE_RED"

//SERVICE
export const CREATE_PLACEDSTUDENT = "CREATE_PLACEDSTUDENT"
export const CREATE_PLACEDSTUDENT_RED = "CREATE_PLACEDSTUDENT_RED"
export const GET_PLACEDSTUDENT = "GET_PLACEDSTUDENT"
export const GET_PLACEDSTUDENT_RED = "GET_PLACEDSTUDENT_RED"
export const UPDATE_PLACEDSTUDENT = "UPDATE_PLACEDSTUDENT"
export const UPDATE_PLACEDSTUDENT_RED = "UPDATE_PLACEDSTUDENT_RED"
export const DELETE_PLACEDSTUDENT = "DELETE_PLACEDSTUDENT"
export const DELETE_PLACEDSTUDENT_RED = "DELETE_PLACEDSTUDENT_RED"

export const CREATE_APPLICATION = "CREATE_APPLICATION"
export const CREATE_APPLICATION_RED = "CREATE_APPLICATION_RED"
export const GET_APPLICATION = "GET_APPLICATION"
export const GET_APPLICATION_RED = "GET_APPLICATION_RED"
export const UPDATE_APPLICATION = "UPDATE_APPLICATION"
export const UPDATE_APPLICATION_RED = "UPDATE_APPLICATION_RED"
export const DELETE_APPLICATION = "DELETE_APPLICATION"
export const DELETE_APPLICATION_RED = "DELETE_APPLICATION_RED"

export const CREATE_PLACEMENTAPPLICATION = "CREATE_PLACEMENTAPPLICATION"
export const CREATE_PLACEMENTAPPLICATION_RED = "CREATE_PLACEMENTAPPLICATION_RED"
export const GET_PLACEMENTAPPLICATION = "GET_PLACEMENTAPPLICATION"
export const GET_PLACEMENTAPPLICATION_RED = "GET_PLACEMENTAPPLICATION_RED"
export const UPDATE_PLACEMENTAPPLICATION = "UPDATE_PLACEMENTAPPLICATION"
export const UPDATE_PLACEMENTAPPLICATION_RED = "UPDATE_PLACEMENTAPPLICATION_RED"
export const DELETE_PLACEMENTAPPLICATION = "DELETE_PLACEMENTAPPLICATION"
export const DELETE_PLACEMENTAPPLICATION_RED = "DELETE_PLACEMENTAPPLICATION_RED"