const AchievementRouter = require('./AchievementRoutes')
const BannerRouter = require('./BannerRoutes')
const PlacementRouter = require('./PlacementRoutes')
const CareerRouter = require('./CareerRoutes')
const TeamsRouter = require('./TeamRoutes')
const TechStackRouter = require('./TechStackRoutes')
const UserRouter = require('./UserRoutes')
const WhyChooseUsRouter = require('./WhyChooseUsRoutes')
const TestimonialRouter = require('./TestimonialRoutes')
const PortfolioRouter = require('./PortfolioRoutes')
const AboutRouter = require('./AboutRoutes')
const BlogRouter = require('./BlogRoutes')
const ServiceRouter = require('./ServiceRoutes')
const SubServiceRouter = require('./SubServiceRoutes')
const PlacedStudentRouter = require('./PlacedStudentRoutes')
const NewsletterRouter = require('./NewsletterRoutes')
const ContactUsRouter = require('./ContactUsRoutes')
const ApplicationRouter = require('./ApplicationRoutes')
const PlacementApplicationRouter = require('./PlacementApplicationRoutes')

const Router = require('express').Router()

Router.use("/user", UserRouter)
Router.use("/teams", TeamsRouter)
Router.use("/banner", BannerRouter)
Router.use("/whychooseus", WhyChooseUsRouter)
Router.use("/techstack", TechStackRouter)
Router.use("/placement", PlacementRouter)
Router.use("/career", CareerRouter)
Router.use("/achievement", AchievementRouter)
Router.use("/testimonial", TestimonialRouter)
Router.use("/portfolio", PortfolioRouter)
Router.use("/about", AboutRouter)
Router.use("/blog", BlogRouter)
Router.use("/service", ServiceRouter)
Router.use("/subservice", SubServiceRouter)
Router.use("/placedstudent", PlacedStudentRouter)
Router.use("/newsletter", NewsletterRouter)
Router.use("/contactus", ContactUsRouter)
Router.use("/application", ApplicationRouter)
Router.use("/placementApplication", PlacementApplicationRouter)

module.exports = Router